version: '3.8'
services:
  backend:
    build:
      context: ./fixnflow-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://salilgupta332:12345@cluster0.mqg9lbb.mongodb.net/fixnflowDB?retryWrites=true&w=majority
      - JWT_SECRET=123456789abcdef
    

  frontend:
    build:
      context: ./fixnflow-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  
