apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fixnflow
spec:
  selector:
    app: fixnflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort
